---
- name: Check ruby version
  shell: /bin/bash -lc "rbenv versions | grep {{ rbenv_ruby_version }}"
  sudo_user: "{{ item }}"
  register: ruby_installed
  ignore_errors: yes
  with_items: rbenv_users
  always_run: yes
  tags:
    - rbenv

- name: Install selected ruby version
  shell: /bin/bash -lc "rbenv install {{ rbenv_ruby_version }}"
  when: item[0].rc != 0 and rbenv_with_patch == ''
  sudo_user: "{{ item[1] }}"
  with_together:
    - ruby_installed.results
    - rbenv_users
  tags:
    - rbenv

- name: Install patched ruby
  shell: /bin/bash -lc "curl -fsSL {{rbenv_with_patch}} | rbenv install --patch {{ rbenv_ruby_version }}"
  when: item[0].rc != 0 and rbenv_with_patch != ''
  sudo_user: "{{ item[1] }}"
  with_together:
    - ruby_installed.results
    - rbenv_users
  tags:
    - rbenv

- name: Set installed ruby as global
  shell: /bin/bash -lc "rbenv global {{ rbenv_ruby_version }} && rbenv rehash"
  when: item[0].rc != 0
  sudo_user: "{{ item[1] }}"
  with_together:
    - ruby_installed.results
    - rbenv_users
  tags:
    - rbenv
