---
- name: "[system] Checkout rbenv_repo"
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_root }}"
    version: "{{ rbenv_version }}"
    accept_hostkey: true
    force: true
  tags:
    - rbenv

- name: "[system] Create plugins directory"
  file: state=directory path={{ rbenv_root }}/plugins
  tags:
    - rbenv

- name: "[system] Install plugins"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ rbenv_root }}/plugins/{{ item.name }}"
    version: "{{ item.version }}"
    accept_hostkey: true
  with_items: " {{ rbenv_plugins }}"
  tags:
    - rbenv
