---
- name: "[user] Set default-gems"
  copy: src=default-gems dest={{ rbenv_root }}/default-gems
  when: item != "root"
  with_items: "{{ rbenv_users }}"
  become_user: "{{ item }}"
  tags:
    - rbenv

- name: "[user] Set gemrc"
  copy: src=gemrc dest=~/.gemrc
  when: item != "root"
  with_items: "{{ rbenv_users }}"
  become_user: "{{ item }}"
  tags:
    - rbenv

- name: "[user] Set vars"
  copy: src=vars dest={{ rbenv_root }}/vars
  when: item != "root"
  with_items: "{{ rbenv_users }}"
  become_user: "{{ item }}"
  tags:
    - rbenv
